### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#19]
We can't use the binary file to read the timezone information like it's done on the JVM.

There is some discussion¹ about implementing a reader for the format moment.js uses² and then just use these files in the browser.

¹ https://github.com/js-joda/js-joda/issues/24
² https://github.com/moment/moment-timezone

**Comment by jtcwang** [comment]
Just wondering what's the progress on this is? It seems like this was blocked by various issues like Locales and source of timezone data. How can I help to get this implemented?

**Comment by cquiroz** [comment]
I'm working on my own fork of the project to support timezones. I've done a fair amount of progress but time zone support is a fairly large subject. Already some of the tests are working but there is still some data to parse to solve non fixed time zones and DST

Feel free to discuss the topic at https://github.com/cquiroz/scala-java-time/issues/9

**Comment by soc** [comment]
This project is discontinued.
