### ISSUE TITLE
Formatting support

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#20]
Formatters have a few dependencies on classes outside `java.time` which are currently not implemented in Scala.js.

A [toy example](https://github.com/soc/threetenbp-js-example/blob/master/src/main/scala/threetenbpjsexample/Main.scala#L35) demonstrates which [external dependencies](https://github.com/soc/threetenbp-js-example/tree/master/src/main/scala/java) ("external" in the sense of "not in the `java.time` package") are required.

It would be necessary to either provide implementations of these classes, or replace them with calls to the browser's JavaScript API.

**Comment by mkotsbak** [comment]
There is even one missing dependency indirectly: https://github.com/cquiroz/scala-java-locales/issues/50

**Comment by mkotsbak** [comment]
Actually currently it is called like this: toLowerCase(Locale.ENGLISH) so that it could be replaced with just toLowerCase() and used the default Locale, which in SJS would be English.

**Comment by mkotsbak** [comment]
And there are more:

```
[error] Referring to non-existent class java.util.ServiceLoader$
[error]   called from org.threeten.bp.zone.ZoneRulesProvider$.<init>()
[error]   called from org.threeten.bp.ZoneId$.getAvailableZoneIds()java.util.Set
[error]   called from org.threeten.bp.format.DateTimeFormatterBuilder$ZoneTextPrinterParser.parse(org.threeten.bp.format.DateTimeParseContext,java.lang.CharSequence,scala.Int)scala.Int
```

**Comment by soc** [comment]
Hi @mkotsbak!

- toLowerCase: Yes we discussed toLowerCase(Locale) recently. The issue is that replacing `toLowerCase(Locale.ENGLISH)` with `toLowerCase()` would result in the wrong behavior on the JVM. So we would basically need to create a forwarder instead, and provide implementation-specific implementations.
- ZoneRulesProvider: Should already be fixed in https://github.com/soc/scala-java-time/commit/9c423aae6067f0a5b7751907c7d6144c77624b6c

**Comment by mkotsbak** [comment]
Ah that is true, if it changes anything in the behaviour, then the calls probably needs to be diverting between the platforms.

**Comment by cquiroz** [comment]
I've been checking the algorithm of `toLowerCase` and the locale parameters is only important in a few specific locales, `tr`, `lv`, `az` and `el`, thus I'd expect `toLowerCase(Locale.ENGLISH)` to be the same as `toLowerCase`.

@soc Why do you think the behavior is different on the JVM?

**Comment by soc** [comment]
@cquiroz `toLowerCase` is locale-dependent on the JVM. So if you are in one of those locales, you _will_ get different results.

**Comment by mkotsbak** [comment]
Yes, but when are characters from those special locales inserted in a pattern that anyway is going to be handled as english locale? Do you have an example?

If another locale is requested, .toFormatter(locale) is run on that afterwards anyway: https://github.com/ThreeTen/threetenbp/blob/456f648b4e02ace2998bf8aa2ba6e3412eaa83e0/src/main/java/org/threeten/bp/format/DateTimeFormatter.java#L788

**Comment by soc** [comment]
https://github.com/soc/scala-java-time/pull/38

**Comment by soc** [comment]
@mkotsbak The problem is that if we start accepting all locales, we also have to test all locales, and I think in this case there is no point in providing a "feature" that the official API lacks, and no one even wants.

**Comment by mkotsbak** [comment]
Ok, the PR seems like a good, low risk solution :)

**Comment by mkotsbak** [comment]
Wow, my code actually works now, both:
`LocalDate.parse(date, DateTimeFormatter.ofPattern("dd.MM.yyyy"))`
and
`LocalDate.parse(date, DateTimeFormatter.ofPattern("dd.MM.yyyy", Locale.GERMAN))`

Is there any more dependencies missing then or could this issue be closed?

**Comment by cquiroz** [comment]
Great! does it work ok the other way around? printing with format?

**Comment by mkotsbak** [comment]
Good point, I actually need that too, will test.

**Comment by mkotsbak** [comment]
Printing with format also works fine, both with and without Locale specified, like this: :)

`someDate.format(DateTimeFormatter.ofPattern("dd.MM.yyyy"))`

**Comment by mkotsbak** [comment]
But then I tried `DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)` and it did not work as expected (using browser's preferred locale).

I think that one should be possible to implement by using some of these:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

If it is feasible, should we open another issue for that?

**Comment by cquiroz** [comment]
What exactly didn't work?

**Comment by cquiroz** [comment]
Perhaps you need to explicitly set the default locale using `Locale.setDefault` if these calls require the default java `Locale`

**Comment by mkotsbak** [comment]
It did not work in the sense that it used the default locale English instead of my browser's preferred language. For features supported by JS I think we should use those instead of using the default locale.

**Comment by soc** [comment]
@mkotsbak I think it working that way was done intentionally by @cquiroz, because otherwise you would need to ship _all_ locales ever invented.
@cquiroz' approach allows you to pick the locales you want to support, and the rest gets removed as unused code.

**Comment by cquiroz** [comment]
Java-locales pretty much assumes that there must be a default locale, On the JVM it is set by the platform. On the browser environment there is no single way to find a locale so my recommendation is to set the default locale at the beginning of your application like

`Locale.setDefault(Locale.GERMAN)`

`scala-java-locales` arbitrarinly sets `Locale.ENGLISH` as the default. That is a design decision which IMHO is better than `null` or removing all the methods requiring a default. `Locale.ENGLISH` is the logical selection to be compatible with some `Scala.js` implementation

**Comment by mkotsbak** [comment]
@soc I haven't tried them, so I don't know how reliable they are, and not all people set their preferred language in the browser.

But how it is now forces us to either ask the user what locale to use if the application is used in multiple countries, or do a server request and let the server tell the client the preferred locales sent in the request headers.

**Comment by cquiroz** [comment]
I think that is the right approach, your application should either know the locale, e.g. because of the user settings or learn it via one of the different approaches like the request headers you mention

If you think about it, the browser at most could tell you the locale of your OS, but you could well be looking at a page on another language. My OS is set to english but i regularly read news in spanish and finnish

**Comment by soc** [comment]
This project is discontinued.
