### ISSUE TITLE
Test support on Scala.js

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#21]
Tests currently depend the TestNG testing framework, which doesn't exist on Scala.js.

Either replace it with something supported on Scala.js or implement enough parts of TestNG in Scala to be able to run the tests on Scala.js.

**Comment by soc** [comment]
Replacing TestNG tests with e. g. JUnit tests is pretty straight forward and has low overhead, but TestNG's `@DataProvider` annotation is a real pain as no other Scala.js-supported testing framework has remotely the same API.

I see roughly two options:
- Create an extension for Junit (or some other Scala.js-supported testing framework) that understands these TestNG annotations
- Rewrite all usages of TestNG's `@DataProvider`

**Comment by soc** [comment]
https://github.com/scala-js/scala-js/pull/2535

**Comment by soc** [comment]
After the TestNG plugin is available, we can have a look at adapting the build system and changing the tests to drop the TestNGSuite dependency on ScalaTest again: https://github.com/soc/scala-java-time/tree/topic/testng-conversion

**Comment by antonkulaga** [comment]
What I can say right now it that it crashes on Scalajs even with simple LocalDateTime.now

**Comment by soc** [comment]
What crashes?

**Comment by antonkulaga** [comment]
My scalajs app whenever I have simple LocalDateTime.now call there

**Comment by soc** [comment]
Well, yes. As mentioned in the readme timezone support hasn't been implemented yet.

**Comment by soc** [comment]
This project is discontinued.
