### ISSUE TITLE
Rename org.threeten.bp to java.time

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#22]
To be a drop-in replacement for `java.time` in Scala.js, we need to have the same package name.

Renaming is an issue because JDKs >= 8 already have these classes in their standard library, and our classes won't even be loaded. (This is an issue because we currently rely on executing on the JVM because our tests only run on the JVM, but not Scala.js (see #21)).

**Comment by mkotsbak** [comment]
Isn't the test issue solved now, so that this rename can be made?

**Comment by soc** [comment]
No, not yet! I'd still like to run the tests on the JVM, even if I get the test running on JS in a few days...

**Comment by mkotsbak** [comment]
Hmm ok, so could it be a solution to trigger a copy/rename in sbt before running the tests?

**Comment by soc** [comment]
That's possible, but I'm not sure how much effort that would be vs. running it on some OpenJDK7 version for testing.

**Comment by soc** [comment]
This project is discontinued.
