### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#23]
The JS API lacks any equivalent to `java.util.Locale` which we could use, so it seems necessary to implement this class from scratch.

**Comment by cquiroz** [comment]
I made a proposal to the scala.js about `Locale` at
https://gist.github.com/cquiroz/1aac347d2277fddbc8c8ca4347844b83

Let me know if you have any comments

**Comment by soc** [comment]
I think this looks very good! I think providing `Locale` is harder than the alternatives you mentioned, but will vastly reduce the amount of code that would need to be adapted by developers porting to Scala.js. Imho your proposal is the right way to go.

Regarding LocaleRegistry: I think we will find a way to not incur unnecessary overhead, either via dead-code elimination, via some build setting, or some compression scheme. I wouldn't worry to much about it right now.

**Comment by cquiroz** [comment]
Great to hear. I think this should go straight to the scala.js project as it is of general use

**Comment by soc** [comment]
In the end everything outside java.time should probably end up in the main project, but I think during development it would be better to keep those classes in this project.

This makes it much easier to test changes. Otherwise we would have to wait for each improvement to be merged and _published_ or have to build and publish javalibs locally just to test.

**Comment by cquiroz** [comment]
I have progressed quite a bit on the Locale front but it is a vast subject. Right now I'm able to parse locales and produce number symbols. Date symbols is coming soon

**Comment by soc** [comment]
Wow, that's cool! I looked a bit into implementing `Calendar` and `GregorianCalendar` recently so I think I have an idea about the mess you have to deal with these badly designed classes! Thanks!

**Comment by soc** [comment]
This project is discontinued.
