### ISSUE TITLE
Test failures in TestDateTimeFormatters

### ISSUE THREAD

**Issue by soc** [soc/scala-java-time#35]
`org.threeten.bp.format.TestDateTimeFormatters` didn't receive the `extends TestNGSuite` treatment until https://github.com/soc/scala-java-time/commit/eedb0b6872ebdc50b012db8ce321ffb0819ce898 so it wasn't tested before.

Running the tests discovered some failures which are basically a variation of three different causes:

1. Spurious "Z" in formatted string
2. Spurious ":00" seconds in formatted string
3. Formatter not throwing `DateTimeException` when it is supposed to do.

Full list of failures:

- test_print_basicIsoDate:
  - Spurious "Z" in formatted string

- test_print_basicIsoDate_fields:
  - Spurious "Z" in formatted string

- isoDate:
  - Spurious "Z" in formatted string
  - DateTimeFormatter.ISO_DATE.format(test) doesn't seem to throw an exception when it is supposed to do

- isoDateTime:
  - Spurious "Z" in formatted string
  - Spurious ":00" seconds in formatted string
  - Spurious "Z[Europe/Paris]" in formatted string

- isoLocalDate:
  - Spurious "Z" in formatted string
  - DateTimeFormatter.ISO_LOCAL_DATE.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoLocalDateTime:
  - Spurious ":00" seconds in formatted string
  - DateTimeFormatter.ISO_LOCAL_DATE_TIME.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoLocalTime:
  - Spurious ":00" seconds in formatted string
  - DateTimeFormatter.ISO_LOCAL_TIME.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoOffsetDate:
  - DateTimeFormatter.ISO_OFFSET_DATE.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoOffsetDateTime:
  - Spurious ":00" seconds in formatted string
  - DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoOffsetTime:
  - Spurious ":00" seconds in formatted string
  - DateTimeFormatter.ISO_OFFSET_TIME.format(test) doesn't seem to throw an exception when it is supposed to do

- test_print_isoOrdinalDate: Spurious "Z" in formatted string

- test_print_isoTime:
  - DateTimeFormatter.ISO_TIME.format(test) doesn't seem to throw an exception when it is supposed to do
  - Spurious "Z" in formatted string
  - Spurious ":00" seconds in formatted string

- test_print_isoWeekDate_fields: Spurious "Z" in formatted string

- print_isoZonedDateTime: DateTimeFormatter.ISO_ZONED_DATE_TIME.format(test) doesn't seem to throw an exception when it is supposed to do

Full gist: https://gist.github.com/soc/52851011a1cddda4f26fd284e1baaf6e

**Comment by soc** [comment]
Ok, I got this!

`java.util.HashMap[TemporalField, Long]` ==> `java.util.HashMap[TemporalField, java.lang.Long]`

**Comment by cquiroz** [comment]
👍

**Comment by soc** [comment]
:-)

**Comment by soc** [comment]
Fixed in https://github.com/soc/scala-java-time/commit/f30a74613f86e2950fbccc1a34030369b31bb1a5.
