### ISSUE TITLE
java.sql.Timestamp conversion support

### ISSUE THREAD

**Issue by danielyli** [soc/scala-java-time#41]
`java.sql.Timestamp` has functions to convert from and to `java.time.Instant`s, but of course they can't be used here.  It'd be nice to have conversion support in this library, maybe as a `RichInstant` to avoid polluting the API.

**Comment by soc** [comment]
@danielyli I think your suggestion makes sense, we just need to find a way to implement it without depending on `java.sql.Timestamp`. As I currently see it, the only option is to create a tiny new library that depends on that type and can be included as necessary by developers. Not sure whether the complexity is worth it though.
Can you think of a better approach?

**Comment by soc** [comment]
This project is discontinued.
