### ISSUE TITLE
Implicit ordering for LocalDate, LocalDateTime, ZonedDateTime

### ISSUE THREAD

**Issue by danielyli** [soc/scala-java-time#42]
When I try to sort a sequence of `LocalDate`, `LocalDateTime`, or `ZonedDateTime` objects, I get an error:

```
scala> def foo(xs: Seq[LocalDate]) = xs.sorted
<console>:15: error: diverging implicit expansion for type scala.math.Ordering[org.threeten.bp.LocalDate]
starting with method $conforms in object Predef
       def foo(xs: Seq[LocalDate]) = xs.sorted

scala> def foo(xs: Seq[LocalDateTime]) = xs.sorted
<console>:15: error: diverging implicit expansion for type scala.math.Ordering[org.threeten.bp.LocalDateTime]
starting with method $conforms in object Predef
       def foo(xs: Seq[LocalDateTime]) = xs.sorted

scala> def foo(xs: Seq[ZonedDateTime]) = xs.sorted
<console>:15: error: diverging implicit expansion for type scala.math.Ordering[org.threeten.bp.ZonedDateTime]
starting with method $conforms in object Predef
       def foo(xs: Seq[ZonedDateTime]) = xs.sorted
```

Why is ordering not supported for these types?  It seems to me orderings for the first two are intuitive and for the last one can be done with a behind-the-scenes conversion to `Instant`.

**Comment by soc** [comment]
They implement `Comparable`, but not `Ordered`. Some investigation would be needed whether they could implement `Ordered` or provide an `Ordering` while not breaking compatibility with the JDK implementation.

**Comment by vpavkin** [comment]
@danielyli there's actualy an implicit conversion to `scala.math.Ordering` for `Comparable`s.
It's just not available by default, try adding `import scala.math.Ordering.Implicits._`

**Comment by soc** [comment]
This project is discontinued.
